(*
 *  This file is part of the Watson Conversation Service OCaml API project.
 *
 * Copyright 2016-2017 IBM Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *)

(** Json utilities. *)

open Wcs_t


val read_json_file : (Yojson.lexer_state -> Lexing.lexbuf -> 'a) -> string -> 'a
(**
   [read_json_file reader fname] reads the file [fname] using the
   reader [reader] generated by atdgen.
*)

val null : json
(** The [null] value of JSON. *)

val set : json -> string -> json -> json
(**
   [set o x v] add (or replace) the a field [x] of the object [o] with
   value [v].
*)

val get : json -> string -> json option
(**
   [get o x] gets the value of the field [x] of the object [o].
*)

val take : json -> string -> json * json option
(**
   [take o x] gets the value of the field [x] of the object [o] and
   remove the field from the object. The left part of the return value
   is the modified object and the right part is the value of the
   field.
*)

val assign : json list -> json
(**
   [assign [o1; ...; on]] create a json object that contains all the
   fields of the objets [o1], ..., [on]. It is similare the the JavaScript
   function [Object.assing({}, o1, ... on)].
*)


(** {6 Settes and getters} *)

(** {8 Boolean fields} *)

val set_bool : json -> string -> bool -> json
(**
   [set_bool o x b] sets the a field [x] of the object [o] with value
   [b].
*)

val get_bool : json -> string -> bool option
(**
   [get_bool o x] gets the value of the field [x] of the object [o].
*)

(** {8 String fields} *)

val set_string : json -> string -> string -> json
(**
   [set_string o x x] sets the a field [x] of the object [o] with string
   [s].
*)

val get_string : json -> string -> string option
(**
   [get_string o x] gets the value of the field [x] of the object [o].
*)

val take_string : json -> string -> json * string option
(**
   [take_string o x] takes the value of the field [x] of the object [o].
*)


(** {6 Conversion of Wcs data structures to JSON} *)

val of_workspace_response : workspace_response -> json

val of_pagination_response : pagination_response -> json

val of_list_workspaces_request : list_workspaces_request -> json

val of_list_workspaces_response : list_workspaces_response -> json

val of_intent_example : intent_example -> json

val of_intent_def : intent_def -> json

val of_entity_value : entity_value -> json

val of_entity_def : entity_def -> json

val of_next_step : next_step -> json

val of_output_def : output_def -> json

val of_dialog_node : dialog_node -> json

val of_workspace : workspace -> json

val of_input : input -> json

val of_entity : entity -> json

val of_output : output -> json

val of_message_request : message_request -> json

val of_message_response : message_response -> json

val of_create_response : create_response -> json

val of_get_workspace_request : get_workspace_request -> json

val of_action : action -> json

val of_action_def : action_def -> json

val of_log_entry : log_entry -> json

val of_logs_request : logs_request -> json

val of_logs_response : logs_response -> json
